/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BudgetCategory = { 'other' : null } |
  { 'food' : null } |
  { 'activities' : null } |
  { 'flights' : null } |
  { 'hotels' : null };
export interface BudgetEntry {
  'id' : string,
  'title' : string,
  'plannedAmount' : number,
  'tripId' : string,
  'category' : BudgetCategory,
  'spentAmount' : number,
}
export type ChecklistCategory = { 'todos' : null } |
  { 'places' : null } |
  { 'packing' : null };
export interface ChecklistItem {
  'id' : string,
  'checked' : boolean,
  'createdAt' : Time,
  'tripId' : string,
  'text' : string,
  'category' : ChecklistCategory,
}
export interface Folder {
  'id' : string,
  'name' : string,
  'createdAt' : Time,
  'tripId' : string,
}
export interface ItineraryDay {
  'id' : string,
  'title' : string,
  'sortOrder' : bigint,
  'date' : string,
  'tripId' : string,
}
export interface ItineraryEvent {
  'id' : string,
  'sortOrder' : bigint,
  'time' : string,
  'description' : string,
  'dayId' : string,
}
export interface MediaItem {
  'id' : string,
  'createdAt' : Time,
  'fileName' : string,
  'blobId' : string,
  'mediaType' : MediaType,
  'parentId' : string,
  'parentType' : string,
}
export type MediaType = { 'video' : null } |
  { 'image' : null };
export interface Subfolder {
  'id' : string,
  'name' : string,
  'createdAt' : Time,
  'folderId' : string,
}
export type Time = bigint;
export interface Trip {
  'id' : string,
  'name' : string,
  'createdAt' : Time,
  'notes' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBudgetEntry' : ActorMethod<
    [string, string, BudgetCategory, string, number, number],
    undefined
  >,
  'createChecklistItem' : ActorMethod<
    [string, string, ChecklistCategory, string],
    undefined
  >,
  'createFolder' : ActorMethod<[string, string, string], undefined>,
  'createItineraryDay' : ActorMethod<
    [string, string, string, string, bigint],
    undefined
  >,
  'createItineraryEvent' : ActorMethod<
    [string, string, string, string, bigint],
    undefined
  >,
  'createMediaItem' : ActorMethod<
    [string, string, string, string, string, MediaType],
    undefined
  >,
  'createSubfolder' : ActorMethod<[string, string, string], undefined>,
  'createTrip' : ActorMethod<[string, string, string], undefined>,
  'deleteBudgetEntry' : ActorMethod<[string], undefined>,
  'deleteChecklistItem' : ActorMethod<[string], undefined>,
  'deleteFolder' : ActorMethod<[string], undefined>,
  'deleteItineraryDay' : ActorMethod<[string], undefined>,
  'deleteItineraryEvent' : ActorMethod<[string], undefined>,
  'deleteMediaItem' : ActorMethod<[string], undefined>,
  'deleteSubfolder' : ActorMethod<[string], undefined>,
  'deleteTrip' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTrip' : ActorMethod<[string], Trip>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listBudgetEntriesByTrip' : ActorMethod<[string], Array<BudgetEntry>>,
  'listChecklistItemsByTripAndCategory' : ActorMethod<
    [string, ChecklistCategory],
    Array<ChecklistItem>
  >,
  'listFoldersByTrip' : ActorMethod<[string], Array<Folder>>,
  'listItineraryDaysByTrip' : ActorMethod<[string], Array<ItineraryDay>>,
  'listItineraryEventsByDay' : ActorMethod<[string], Array<ItineraryEvent>>,
  'listMediaItemsByParent' : ActorMethod<[string, string], Array<MediaItem>>,
  'listSubfoldersByFolder' : ActorMethod<[string], Array<Subfolder>>,
  'listTrips' : ActorMethod<[], Array<Trip>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBudgetEntry' : ActorMethod<
    [string, string, number, number],
    undefined
  >,
  'updateChecklistItem' : ActorMethod<[string, string, boolean], undefined>,
  'updateFolder' : ActorMethod<[string, string], undefined>,
  'updateItineraryDay' : ActorMethod<
    [string, string, string, bigint],
    undefined
  >,
  'updateItineraryEvent' : ActorMethod<
    [string, string, string, bigint],
    undefined
  >,
  'updateSubfolder' : ActorMethod<[string, string], undefined>,
  'updateTrip' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];