/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BudgetCategory = IDL.Variant({
  'other' : IDL.Null,
  'food' : IDL.Null,
  'activities' : IDL.Null,
  'flights' : IDL.Null,
  'hotels' : IDL.Null,
});
export const ChecklistCategory = IDL.Variant({
  'todos' : IDL.Null,
  'places' : IDL.Null,
  'packing' : IDL.Null,
});
export const MediaType = IDL.Variant({
  'video' : IDL.Null,
  'image' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const Trip = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'notes' : IDL.Text,
});
export const BudgetEntry = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'plannedAmount' : IDL.Float64,
  'tripId' : IDL.Text,
  'category' : BudgetCategory,
  'spentAmount' : IDL.Float64,
});
export const ChecklistItem = IDL.Record({
  'id' : IDL.Text,
  'checked' : IDL.Bool,
  'createdAt' : Time,
  'tripId' : IDL.Text,
  'text' : IDL.Text,
  'category' : ChecklistCategory,
});
export const Folder = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'tripId' : IDL.Text,
});
export const ItineraryDay = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'date' : IDL.Text,
  'tripId' : IDL.Text,
});
export const ItineraryEvent = IDL.Record({
  'id' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'dayId' : IDL.Text,
});
export const MediaItem = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : Time,
  'fileName' : IDL.Text,
  'blobId' : IDL.Text,
  'mediaType' : MediaType,
  'parentId' : IDL.Text,
  'parentType' : IDL.Text,
});
export const Subfolder = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'folderId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBudgetEntry' : IDL.Func(
      [IDL.Text, IDL.Text, BudgetCategory, IDL.Text, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'createChecklistItem' : IDL.Func(
      [IDL.Text, IDL.Text, ChecklistCategory, IDL.Text],
      [],
      [],
    ),
  'createFolder' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createItineraryDay' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'createItineraryEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'createMediaItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, MediaType],
      [],
      [],
    ),
  'createSubfolder' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createTrip' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteBudgetEntry' : IDL.Func([IDL.Text], [], []),
  'deleteChecklistItem' : IDL.Func([IDL.Text], [], []),
  'deleteFolder' : IDL.Func([IDL.Text], [], []),
  'deleteItineraryDay' : IDL.Func([IDL.Text], [], []),
  'deleteItineraryEvent' : IDL.Func([IDL.Text], [], []),
  'deleteMediaItem' : IDL.Func([IDL.Text], [], []),
  'deleteSubfolder' : IDL.Func([IDL.Text], [], []),
  'deleteTrip' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTrip' : IDL.Func([IDL.Text], [Trip], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listBudgetEntriesByTrip' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BudgetEntry)],
      ['query'],
    ),
  'listChecklistItemsByTripAndCategory' : IDL.Func(
      [IDL.Text, ChecklistCategory],
      [IDL.Vec(ChecklistItem)],
      ['query'],
    ),
  'listFoldersByTrip' : IDL.Func([IDL.Text], [IDL.Vec(Folder)], ['query']),
  'listItineraryDaysByTrip' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ItineraryDay)],
      ['query'],
    ),
  'listItineraryEventsByDay' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ItineraryEvent)],
      ['query'],
    ),
  'listMediaItemsByParent' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(MediaItem)],
      ['query'],
    ),
  'listSubfoldersByFolder' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Subfolder)],
      ['query'],
    ),
  'listTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBudgetEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'updateChecklistItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
  'updateFolder' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateItineraryDay' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'updateItineraryEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'updateSubfolder' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateTrip' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BudgetCategory = IDL.Variant({
    'other' : IDL.Null,
    'food' : IDL.Null,
    'activities' : IDL.Null,
    'flights' : IDL.Null,
    'hotels' : IDL.Null,
  });
  const ChecklistCategory = IDL.Variant({
    'todos' : IDL.Null,
    'places' : IDL.Null,
    'packing' : IDL.Null,
  });
  const MediaType = IDL.Variant({ 'video' : IDL.Null, 'image' : IDL.Null });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const Trip = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'notes' : IDL.Text,
  });
  const BudgetEntry = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'plannedAmount' : IDL.Float64,
    'tripId' : IDL.Text,
    'category' : BudgetCategory,
    'spentAmount' : IDL.Float64,
  });
  const ChecklistItem = IDL.Record({
    'id' : IDL.Text,
    'checked' : IDL.Bool,
    'createdAt' : Time,
    'tripId' : IDL.Text,
    'text' : IDL.Text,
    'category' : ChecklistCategory,
  });
  const Folder = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'tripId' : IDL.Text,
  });
  const ItineraryDay = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'date' : IDL.Text,
    'tripId' : IDL.Text,
  });
  const ItineraryEvent = IDL.Record({
    'id' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'dayId' : IDL.Text,
  });
  const MediaItem = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : Time,
    'fileName' : IDL.Text,
    'blobId' : IDL.Text,
    'mediaType' : MediaType,
    'parentId' : IDL.Text,
    'parentType' : IDL.Text,
  });
  const Subfolder = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'folderId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBudgetEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          BudgetCategory,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
        ],
        [],
        [],
      ),
    'createChecklistItem' : IDL.Func(
        [IDL.Text, IDL.Text, ChecklistCategory, IDL.Text],
        [],
        [],
      ),
    'createFolder' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createItineraryDay' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'createItineraryEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'createMediaItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, MediaType],
        [],
        [],
      ),
    'createSubfolder' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createTrip' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteBudgetEntry' : IDL.Func([IDL.Text], [], []),
    'deleteChecklistItem' : IDL.Func([IDL.Text], [], []),
    'deleteFolder' : IDL.Func([IDL.Text], [], []),
    'deleteItineraryDay' : IDL.Func([IDL.Text], [], []),
    'deleteItineraryEvent' : IDL.Func([IDL.Text], [], []),
    'deleteMediaItem' : IDL.Func([IDL.Text], [], []),
    'deleteSubfolder' : IDL.Func([IDL.Text], [], []),
    'deleteTrip' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTrip' : IDL.Func([IDL.Text], [Trip], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listBudgetEntriesByTrip' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BudgetEntry)],
        ['query'],
      ),
    'listChecklistItemsByTripAndCategory' : IDL.Func(
        [IDL.Text, ChecklistCategory],
        [IDL.Vec(ChecklistItem)],
        ['query'],
      ),
    'listFoldersByTrip' : IDL.Func([IDL.Text], [IDL.Vec(Folder)], ['query']),
    'listItineraryDaysByTrip' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ItineraryDay)],
        ['query'],
      ),
    'listItineraryEventsByDay' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ItineraryEvent)],
        ['query'],
      ),
    'listMediaItemsByParent' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(MediaItem)],
        ['query'],
      ),
    'listSubfoldersByFolder' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Subfolder)],
        ['query'],
      ),
    'listTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBudgetEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'updateChecklistItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
    'updateFolder' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateItineraryDay' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateItineraryEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateSubfolder' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateTrip' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };