/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ItineraryEvent {
    id: string;
    sortOrder: bigint;
    time: string;
    description: string;
    dayId: string;
}
export interface Trip {
    id: string;
    name: string;
    createdAt: Time;
    notes: string;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface MediaItem {
    id: string;
    createdAt: Time;
    fileName: string;
    blobId: string;
    mediaType: MediaType;
    parentId: string;
    parentType: string;
}
export interface BudgetEntry {
    id: string;
    title: string;
    plannedAmount: number;
    tripId: string;
    category: BudgetCategory;
    spentAmount: number;
}
export interface ItineraryDay {
    id: string;
    title: string;
    sortOrder: bigint;
    date: string;
    tripId: string;
}
export interface ChecklistItem {
    id: string;
    checked: boolean;
    createdAt: Time;
    tripId: string;
    text: string;
    category: ChecklistCategory;
}
export interface Subfolder {
    id: string;
    name: string;
    createdAt: Time;
    folderId: string;
}
export interface Folder {
    id: string;
    name: string;
    createdAt: Time;
    tripId: string;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum BudgetCategory {
    other = "other",
    food = "food",
    activities = "activities",
    flights = "flights",
    hotels = "hotels"
}
export enum ChecklistCategory {
    todos = "todos",
    places = "places",
    packing = "packing"
}
export enum MediaType {
    video = "video",
    image = "image"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBudgetEntry(id: string, tripId: string, category: BudgetCategory, title: string, plannedAmount: number, spentAmount: number): Promise<void>;
    createChecklistItem(id: string, tripId: string, category: ChecklistCategory, text: string): Promise<void>;
    createFolder(id: string, tripId: string, name: string): Promise<void>;
    createItineraryDay(id: string, tripId: string, date: string, title: string, sortOrder: bigint): Promise<void>;
    createItineraryEvent(id: string, dayId: string, time: string, description: string, sortOrder: bigint): Promise<void>;
    createMediaItem(id: string, parentType: string, parentId: string, blobId: string, fileName: string, mediaType: MediaType): Promise<void>;
    createSubfolder(id: string, folderId: string, name: string): Promise<void>;
    createTrip(id: string, name: string, notes: string): Promise<void>;
    deleteBudgetEntry(id: string): Promise<void>;
    deleteChecklistItem(id: string): Promise<void>;
    deleteFolder(id: string): Promise<void>;
    deleteItineraryDay(id: string): Promise<void>;
    deleteItineraryEvent(id: string): Promise<void>;
    deleteMediaItem(id: string): Promise<void>;
    deleteSubfolder(id: string): Promise<void>;
    deleteTrip(id: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getTrip(id: string): Promise<Trip>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listBudgetEntriesByTrip(tripId: string): Promise<Array<BudgetEntry>>;
    listChecklistItemsByTripAndCategory(tripId: string, category: ChecklistCategory): Promise<Array<ChecklistItem>>;
    listFoldersByTrip(tripId: string): Promise<Array<Folder>>;
    listItineraryDaysByTrip(tripId: string): Promise<Array<ItineraryDay>>;
    listItineraryEventsByDay(dayId: string): Promise<Array<ItineraryEvent>>;
    listMediaItemsByParent(parentType: string, parentId: string): Promise<Array<MediaItem>>;
    listSubfoldersByFolder(folderId: string): Promise<Array<Subfolder>>;
    listTrips(): Promise<Array<Trip>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateBudgetEntry(id: string, title: string, plannedAmount: number, spentAmount: number): Promise<void>;
    updateChecklistItem(id: string, text: string, checked: boolean): Promise<void>;
    updateFolder(id: string, name: string): Promise<void>;
    updateItineraryDay(id: string, date: string, title: string, sortOrder: bigint): Promise<void>;
    updateItineraryEvent(id: string, time: string, description: string, sortOrder: bigint): Promise<void>;
    updateSubfolder(id: string, name: string): Promise<void>;
    updateTrip(id: string, name: string, notes: string): Promise<void>;
}
import type { BudgetCategory as _BudgetCategory, BudgetEntry as _BudgetEntry, ChecklistCategory as _ChecklistCategory, ChecklistItem as _ChecklistItem, MediaItem as _MediaItem, MediaType as _MediaType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBudgetEntry(arg0: string, arg1: string, arg2: BudgetCategory, arg3: string, arg4: number, arg5: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBudgetEntry(arg0, arg1, to_candid_BudgetCategory_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBudgetEntry(arg0, arg1, to_candid_BudgetCategory_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
            return result;
        }
    }
    async createChecklistItem(arg0: string, arg1: string, arg2: ChecklistCategory, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createChecklistItem(arg0, arg1, to_candid_ChecklistCategory_n12(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChecklistItem(arg0, arg1, to_candid_ChecklistCategory_n12(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async createFolder(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createFolder(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFolder(arg0, arg1, arg2);
            return result;
        }
    }
    async createItineraryDay(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createItineraryDay(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createItineraryDay(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createItineraryEvent(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createItineraryEvent(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createItineraryEvent(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createMediaItem(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: MediaType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMediaItem(arg0, arg1, arg2, arg3, arg4, to_candid_MediaType_n14(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMediaItem(arg0, arg1, arg2, arg3, arg4, to_candid_MediaType_n14(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async createSubfolder(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubfolder(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubfolder(arg0, arg1, arg2);
            return result;
        }
    }
    async createTrip(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTrip(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTrip(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteBudgetEntry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBudgetEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBudgetEntry(arg0);
            return result;
        }
    }
    async deleteChecklistItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChecklistItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChecklistItem(arg0);
            return result;
        }
    }
    async deleteFolder(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFolder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFolder(arg0);
            return result;
        }
    }
    async deleteItineraryDay(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteItineraryDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteItineraryDay(arg0);
            return result;
        }
    }
    async deleteItineraryEvent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteItineraryEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteItineraryEvent(arg0);
            return result;
        }
    }
    async deleteMediaItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMediaItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMediaItem(arg0);
            return result;
        }
    }
    async deleteSubfolder(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubfolder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubfolder(arg0);
            return result;
        }
    }
    async deleteTrip(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrip(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrip(arg0: string): Promise<Trip> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrip(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listBudgetEntriesByTrip(arg0: string): Promise<Array<BudgetEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBudgetEntriesByTrip(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBudgetEntriesByTrip(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async listChecklistItemsByTripAndCategory(arg0: string, arg1: ChecklistCategory): Promise<Array<ChecklistItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listChecklistItemsByTripAndCategory(arg0, to_candid_ChecklistCategory_n12(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listChecklistItemsByTripAndCategory(arg0, to_candid_ChecklistCategory_n12(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFoldersByTrip(arg0: string): Promise<Array<Folder>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFoldersByTrip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFoldersByTrip(arg0);
            return result;
        }
    }
    async listItineraryDaysByTrip(arg0: string): Promise<Array<ItineraryDay>> {
        if (this.processError) {
            try {
                const result = await this.actor.listItineraryDaysByTrip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listItineraryDaysByTrip(arg0);
            return result;
        }
    }
    async listItineraryEventsByDay(arg0: string): Promise<Array<ItineraryEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.listItineraryEventsByDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listItineraryEventsByDay(arg0);
            return result;
        }
    }
    async listMediaItemsByParent(arg0: string, arg1: string): Promise<Array<MediaItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMediaItemsByParent(arg0, arg1);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMediaItemsByParent(arg0, arg1);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSubfoldersByFolder(arg0: string): Promise<Array<Subfolder>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSubfoldersByFolder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSubfoldersByFolder(arg0);
            return result;
        }
    }
    async listTrips(): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTrips();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTrips();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateBudgetEntry(arg0: string, arg1: string, arg2: number, arg3: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBudgetEntry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBudgetEntry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateChecklistItem(arg0: string, arg1: string, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChecklistItem(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChecklistItem(arg0, arg1, arg2);
            return result;
        }
    }
    async updateFolder(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFolder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFolder(arg0, arg1);
            return result;
        }
    }
    async updateItineraryDay(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateItineraryDay(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateItineraryDay(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateItineraryEvent(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateItineraryEvent(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateItineraryEvent(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateSubfolder(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubfolder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubfolder(arg0, arg1);
            return result;
        }
    }
    async updateTrip(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrip(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrip(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_BudgetCategory_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BudgetCategory): BudgetCategory {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_BudgetEntry_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BudgetEntry): BudgetEntry {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ChecklistCategory_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChecklistCategory): ChecklistCategory {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_ChecklistItem_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChecklistItem): ChecklistItem {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_MediaItem_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaItem): MediaItem {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_MediaType_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaType): MediaType {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    plannedAmount: number;
    tripId: string;
    category: _BudgetCategory;
    spentAmount: number;
}): {
    id: string;
    title: string;
    plannedAmount: number;
    tripId: string;
    category: BudgetCategory;
    spentAmount: number;
} {
    return {
        id: value.id,
        title: value.title,
        plannedAmount: value.plannedAmount,
        tripId: value.tripId,
        category: from_candid_BudgetCategory_n22(_uploadFile, _downloadFile, value.category),
        spentAmount: value.spentAmount
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    checked: boolean;
    createdAt: _Time;
    tripId: string;
    text: string;
    category: _ChecklistCategory;
}): {
    id: string;
    checked: boolean;
    createdAt: Time;
    tripId: string;
    text: string;
    category: ChecklistCategory;
} {
    return {
        id: value.id,
        checked: value.checked,
        createdAt: value.createdAt,
        tripId: value.tripId,
        text: value.text,
        category: from_candid_ChecklistCategory_n27(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    createdAt: _Time;
    fileName: string;
    blobId: string;
    mediaType: _MediaType;
    parentId: string;
    parentType: string;
}): {
    id: string;
    createdAt: Time;
    fileName: string;
    blobId: string;
    mediaType: MediaType;
    parentId: string;
    parentType: string;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        fileName: value.fileName,
        blobId: value.blobId,
        mediaType: from_candid_MediaType_n32(_uploadFile, _downloadFile, value.mediaType),
        parentId: value.parentId,
        parentType: value.parentType
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    food: null;
} | {
    activities: null;
} | {
    flights: null;
} | {
    hotels: null;
}): BudgetCategory {
    return "other" in value ? BudgetCategory.other : "food" in value ? BudgetCategory.food : "activities" in value ? BudgetCategory.activities : "flights" in value ? BudgetCategory.flights : "hotels" in value ? BudgetCategory.hotels : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    todos: null;
} | {
    places: null;
} | {
    packing: null;
}): ChecklistCategory {
    return "todos" in value ? ChecklistCategory.todos : "places" in value ? ChecklistCategory.places : "packing" in value ? ChecklistCategory.packing : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: null;
} | {
    image: null;
}): MediaType {
    return "video" in value ? MediaType.video : "image" in value ? MediaType.image : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BudgetEntry>): Array<BudgetEntry> {
    return value.map((x)=>from_candid_BudgetEntry_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChecklistItem>): Array<ChecklistItem> {
    return value.map((x)=>from_candid_ChecklistItem_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MediaItem>): Array<MediaItem> {
    return value.map((x)=>from_candid_MediaItem_n30(_uploadFile, _downloadFile, x));
}
function to_candid_BudgetCategory_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BudgetCategory): _BudgetCategory {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_ChecklistCategory_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChecklistCategory): _ChecklistCategory {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_MediaType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaType): _MediaType {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BudgetCategory): {
    other: null;
} | {
    food: null;
} | {
    activities: null;
} | {
    flights: null;
} | {
    hotels: null;
} {
    return value == BudgetCategory.other ? {
        other: null
    } : value == BudgetCategory.food ? {
        food: null
    } : value == BudgetCategory.activities ? {
        activities: null
    } : value == BudgetCategory.flights ? {
        flights: null
    } : value == BudgetCategory.hotels ? {
        hotels: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChecklistCategory): {
    todos: null;
} | {
    places: null;
} | {
    packing: null;
} {
    return value == ChecklistCategory.todos ? {
        todos: null
    } : value == ChecklistCategory.places ? {
        places: null
    } : value == ChecklistCategory.packing ? {
        packing: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaType): {
    video: null;
} | {
    image: null;
} {
    return value == MediaType.video ? {
        video: null
    } : value == MediaType.image ? {
        image: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
